### PR TITLE
feat: add option to define the theme

### PR DESCRIPTION
**Pull request by Alkindi42**
Hello,

I added the option `let g:mkdp_theme` to set the default theme (#310).

By default the theme is define according to the preferences of the system. You can override this behavior by adding `let g:mkdp_theme = 'dark'` (or light) in your vimrc. Finally in the header you have a button to change the theme on the fly.

Related issues: #331, #315.

### CODE REVIEW

**Comment by BreezyMain** [comment]
Thank you!

**Comment by GaetanLepage** [comment]
Thank you !
Hope this will get merged soon :)

**Comment by Rasukarusan** [comment]
Thank you! This is good PR!

**Comment by iamcco** [comment]
Thanks!

**Pull request merged**
