### PR TITLE
added packer support

### PR DESCRIPTION
**Pull request by RaafatTurki**

### CODE REVIEW

**Comment by rambip** [comment]
I can't find the "MarkdownPreview" command when I install with packer, is it a bug ?

**Comment by RaafatTurki** [comment]
Which `use` command did you use to install it?
I personally use the `prebuild` one and it works flawlessly

`use {'iamcco/markdown-preview.nvim', config = "vim.call('mkdp#util#install')"}`

Do note when `:PackerSync` finishes it's work a second download pops up (only happens in `prebuild` since it has to download the binary)

**Comment by rambip** [comment]
I think the issue came from my npm installation, it works well with the prebuild.

I linked it to #219 

I think this line should be the default to install with packer, maybe you could insist on it in the README ?
I'm not even sure why you would need the 2 other installation methods.

**Comment by RaafatTurki** [comment]
Glad to know it has worked out for you, I was just following the intent of the owner since they already had the `yarn` method in the `vim-plug` setup.
Perhaps he wanted people to have a way to build the plugin in case the released binary got out of sync hence why `yarn` was an option in the 1st place.
Either way I have considered this when I've placed it as the 1st option and will consider emphasizing it further as well.

**Comment by RaafatTurki** [comment]
ah just missclicked it

**Pull request closed without merging**
